<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\core\Citizen.targets" />

  <ItemGroup>
    <Compile Include="..\sharedLogic\cs\ProxyPoolContract.cs" />
    <Compile Include="..\sharedLogic\cs\ProxyPoolHealthContract.cs" />
    <Compile Include="..\sharedLogic\cs\CredenzPath.cs" />
  </ItemGroup>

</Project>
